"""Auto-generated blacklist of structural link pairs for OpenArm.

Generated by auto_blacklist_openarm.py with N=300000 probes
on both arms randomized.
Includes (a) parent-child + same-arm link5<->link7 (URDF artefacts)
and (b) intra-arm pairs whose min distance over all probes
>= 0.0 m (structurally safe).
"""

BLACKLIST_NAME_PAIRS = [
    ("openarm_body_link0", "openarm_left_link0"),
    ("openarm_body_link0", "openarm_left_link1"),
    ("openarm_body_link0", "openarm_left_link2"),
    ("openarm_body_link0", "openarm_right_link0"),
    ("openarm_body_link0", "openarm_right_link1"),
    ("openarm_body_link0", "openarm_right_link2"),
    ("openarm_left_hand", "openarm_left_left_finger"),
    ("openarm_left_hand", "openarm_left_right_finger"),
    ("openarm_left_link0", "openarm_left_link1"),
    ("openarm_left_link1", "openarm_left_link2"),
    ("openarm_left_link1", "openarm_left_link4"),
    ("openarm_left_link2", "openarm_left_link3"),
    ("openarm_left_link2", "openarm_left_link4"),
    ("openarm_left_link3", "openarm_left_link4"),
    ("openarm_left_link3", "openarm_left_link6"),
    ("openarm_left_link4", "openarm_left_link5"),
    ("openarm_left_link4", "openarm_left_link6"),
    ("openarm_left_link4", "openarm_left_link7"),
    ("openarm_left_link5", "openarm_left_link6"),
    ("openarm_left_link5", "openarm_left_link7"),
    ("openarm_left_link6", "openarm_left_hand"),
    ("openarm_left_link6", "openarm_left_left_finger"),
    ("openarm_left_link6", "openarm_left_link7"),
    ("openarm_left_link6", "openarm_left_right_finger"),
    ("openarm_left_link7", "openarm_left_hand"),
    ("openarm_left_link7", "openarm_left_left_finger"),
    ("openarm_left_link7", "openarm_left_right_finger"),
    ("openarm_right_hand", "openarm_right_left_finger"),
    ("openarm_right_hand", "openarm_right_right_finger"),
    ("openarm_right_link0", "openarm_right_link1"),
    ("openarm_right_link1", "openarm_right_link2"),
    ("openarm_right_link1", "openarm_right_link4"),
    ("openarm_right_link2", "openarm_right_link3"),
    ("openarm_right_link2", "openarm_right_link4"),
    ("openarm_right_link3", "openarm_right_link4"),
    ("openarm_right_link3", "openarm_right_link6"),
    ("openarm_right_link4", "openarm_right_link5"),
    ("openarm_right_link4", "openarm_right_link6"),
    ("openarm_right_link4", "openarm_right_link7"),
    ("openarm_right_link5", "openarm_right_link6"),
    ("openarm_right_link5", "openarm_right_link7"),
    ("openarm_right_link6", "openarm_right_hand"),
    ("openarm_right_link6", "openarm_right_left_finger"),
    ("openarm_right_link6", "openarm_right_link7"),
    ("openarm_right_link6", "openarm_right_right_finger"),
    ("openarm_right_link7", "openarm_right_hand"),
    ("openarm_right_link7", "openarm_right_left_finger"),
    ("openarm_right_link7", "openarm_right_right_finger"),
]
